language: ruby
rvm:
- 2.1.10
- 2.2.9
- 2.3.6
- 2.4.3
- 2.5.0
before_install:
- gem update --system
script:
- bundle install
- bundle exec rake
gemfile:
  - gemfiles/fluentd_0.12.gemfile
  - gemfiles/fluentd_0.14.gemfile
